### ISSUE TITLE
bug suppression des messages.

### ISSUE THREAD

**Issue by al3xLvs** [adaur/ajax-chat-for-fluxbb#1]
Salut,

J'ai un bug quand je supprime un message. Quand je rafraîchie la page, juste après la liste des messages ne s'affiche plus. Très étrange car j'ai aucun message d'erreur dans la console.

**Comment by adaur** [comment]
Bizarre, étant donné que tu es le premier à me rapporter ce bug après pas mal d'utilisation. As tu essayé avec d'autres terminaux/installations?

**Comment by al3xLvs** [comment]
oui. J'ai le même soucis ailleurs et sur d'autre pc.

le problème viendrait de ajax-chat?
Pour les retours que j'ai eu le bug apparaît sous chrome, firefox . pour les os linux, mac os et windows.

**Comment by al3xLvs** [comment]
@adaur j'ai fait une petite recherche sur ce bug et visiblement il a été fixé dans la release 0.8.7

```
Bugfixes:
- Fixed case when messages were not displayed to users on page load if last message was deleted - thanks to KEMBL KEMBL.
```

Je ferais une PR à l'occasion

**Comment by adaur** [comment]
Oui, je l'ai fixé sur mon forum manuellement: https://github.com/Frug/AJAX-Chat/issues/47
